### ISSUE TITLE
How to check signature?

### ISSUE THREAD

**Issue by uzman** [michalkonturek/SignatureView#4]
Hi,
how can i check if it is signed or not?
i checked;
    NSData *signatureData = [self.signatureView signatureData];
    if (signatureData.length==0) {
//
}
but if just touched the view nsdata size is greater than 0.
or first i sign the view, then call clear method. nsdata size is still greater than 0.

thanks...

**Comment by michalkonturek** [comment]
``` objc
[self.signatureView isSigned];
```
