### ISSUE TITLE
Signature PNG with transparent background

### ISSUE THREAD

**Issue by almoehi** [michalkonturek/SignatureView#5]
Hi,
is there a way to get the signature PNG with transparent background ?
I played around with several settings of foreground / background color but it always returns the image with white background.

Thanks !

**Comment by michalkonturek** [comment]
I am sure it is possible, but I am afraid I don't have time to develop it in the near future.

**Comment by haemi** [comment]
@almoehi did you ever find a solution/workaround for this?
